import { ArrowUpRight, Code2, BriefcaseBusiness, Mail, Braces, Server, Database, BrainCircuit, Wrench, Bot, Network } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button, TextLink } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { SectionHeading } from '../../components/ui/SectionHeading';
import { HeroSceneLoader } from '../../components/hero/HeroSceneLoader';
import { ProjectGrid } from '../../components/projects/ProjectGrid';
import { EngineeringCard } from '../../components/engineering/EngineeringCard';
import { engineeringTopics } from '../../data/engineering';
import { projects } from '../../data/projects';
import { skillGroups as sharedSkillGroups } from '../../data/skills';
import { GitHubSection } from '../github/GitHubSection';

const skillIcons = { Frontend: Braces, Backend: Server, Database, AI: BrainCircuit, Tools: Wrench };
const skillGroups = sharedSkillGroups.map(group => ({ name: group.title, items: group.items, icon: skillIcons[group.title as keyof typeof skillIcons] }));
const labCards = [{ title: 'Portfolio AI', icon: BrainCircuit }, { title: 'RAG', icon: Network }, { title: 'AI Agents', icon: Bot }];

export default function HomePage() { return <>
  <section className="hero section-wrap"><div className="hero-backdrop" aria-hidden="true"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><span className="status-dot"/> FULL STACK DEVELOPER</span><h1>Building scalable web applications and <span>AI-powered products.</span></h1><p className="hero-description">Full Stack Developer focused on MERN, backend engineering and AI-powered applications.</p><div className="hero-actions"><Button variant="primary" to="/projects" arrow>View Projects</Button><Link to="/contact" className="button button-ghost download-button">Discuss a project <ArrowUpRight size={15}/></Link></div><div className="social-links"><Link to="/contact"><Mail size={16}/> Contact <ArrowUpRight size={12}/></Link></div></div><div className="hero-scene-wrap"><HeroSceneLoader /></div></div><div className="hero-bottom container"><span>INDEPENDENT DEVELOPER <i/> INDIA</span><a href="#about">SCROLL TO EXPLORE <span>↓</span></a></div></section>
  <section className="section-wrap" id="about"><div className="container about-preview"><div><SectionHeading eyebrow="A LITTLE ABOUT ME" title="Thoughtful engineering. Practical outcomes."/><p className="body-copy">I build across the stack, from clear user interfaces to dependable backend services. My current interests include AI and LLM powered applications.</p><TextLink to="/about">More About Me</TextLink></div><div className="about-note"><span className="mono-label">01 / APPROACH</span><p>Start with the problem.<br/>Build with intent.<br/><span>Keep improving.</span></p><div className="note-rule"/></div></div></section>
  <section className="section-wrap section-alt" id="projects"><div className="container"><div className="section-top"><SectionHeading eyebrow="SELECTED WORK" title="Featured projects" description="Engineering case studies, with verified project information added as it becomes available."/></div><ProjectGrid projects={projects.filter(project => project.featured).slice(0, 3)}/><div className="section-action"><Button to="/projects" arrow>View All Projects</Button></div></div></section>
  <section className="section-wrap" id="skills"><div className="container"><div className="section-top"><SectionHeading eyebrow="TOOLKIT" title="Skills & technologies" description="A working toolkit across application development and AI."/><TextLink to="/skills">Explore skills</TextLink></div><div className="skills-grid">{skillGroups.map(group => <Card key={group.name} className="skill-card"><group.icon size={19}/><h3>{group.name}</h3><div className="tag-list">{group.items.map(item => <span key={item}>{item}</span>)}</div></Card>)}</div></div></section>
  <section className="section-wrap section-alt" id="engineering"><div className="container engineering-section"><div className="engineering-header"><SectionHeading eyebrow="ENGINEERING" title="How I build." description="From product idea to reliable software, with a focus on clear structure, API boundaries and practical implementation."/><p className="engineering-intro">I work from the problem outward: define the interface, shape the backend, choose the right data flow, and integrate AI only where it meaningfully supports the product.</p></div><div className="engineering-grid">{engineeringTopics.map((topic, index) => <EngineeringCard key={topic.slug} topic={topic} index={index}/>)}</div></div></section>
  <GitHubSection/>
  <section className="section-wrap" id="ai-lab"><div className="container ai-lab-panel"><div className="ai-copy"><span className="eyebrow">EXPLORATION / 01</span><SectionHeading eyebrow="" title="AI Lab" description="Experiments with LLMs, RAG, AI Agents and intelligent applications."/><TextLink to="/ai-lab">Explore the lab</TextLink></div><div className="lab-cards">{labCards.map((item, i) => <Card key={item.title} className="lab-card"><span className="mono-label">0{i + 1} / EXPERIMENT</span><item.icon size={21}/><h3>{item.title}</h3><span className="lab-status">IN DEVELOPMENT</span></Card>)}</div></div></section>
  <section className="section-wrap contact-section"><div className="container contact-panel"><span className="eyebrow">HAVE A GOOD PROBLEM?</span><h2>Let’s build something<span>.</span></h2><p>Open to thoughtful conversations about products, engineering and AI.</p><div className="hero-actions"><Button variant="primary" to="/contact" arrow>Contact Me</Button><Link className="button button-ghost" to="/projects">View Projects <ArrowUpRight size={15}/></Link></div></div></section>
  </>; }
